//! Runner loop for the MetalTile toolchain.
//!
//! This module implements the protocol loop that the auto-generated
//! `__tile_runner` harness binary calls.  It iterates over registered
//! [`KernelBench`] and [`KernelTest`] inventory entries, handles
//! `--filter`, dispatches GPU work, and streams JSON results to stdout.
//!
//! # Architecture
//!
//! The harness binary is auto-generated by `tile` — kernel authors never
//! see or write it.  The generated `main` function is:
//!
//! ```ignore
//! fn main() {
//!     metaltile::runner::run(metaltile::runner::Args::from_env());
//! }
//! ```

use std::io::Write;

use metaltile_core::{
    DType,
    all_benches,
    all_tests,
    bench::{KernelBench, KernelTest},
    protocol::{BenchResult, ProtocolMessage, TestResult},
};

/// Runner command-line arguments passed by the auto-generated harness.
pub struct Args {
    /// Subcommand: `bench`, `test`, `build`, or `inspect`.
    pub command: Command,
    /// Optional filter string (case-insensitive substring match on name).
    pub filter: Option<String>,
}

/// Runner subcommands.
pub enum Command {
    /// Run benchmarks.
    Bench,
    /// Run correctness tests.
    Test,
}

impl Args {
    /// Parse arguments from `std::env::args()`.
    ///
    /// Expected format: `__tile_runner [-- bench|test [--filter <f>]]`
    pub fn from_env() -> Self {
        let args: Vec<String> = std::env::args().collect();
        // Skip binary name; look for subcommand after `--` separator.
        let cmd_idx = args.iter().position(|a| a == "bench" || a == "test");
        let filter =
            args.windows(2).find(|w| w[0] == "--filter" || w[0] == "-f").map(|w| w[1].clone());
        let command = match cmd_idx {
            Some(i) if args[i] == "test" => Command::Test,
            _ => Command::Bench,
        };
        Args { command, filter }
    }
}

/// Run the protocol loop: discover benches/tests, dispatch, and stream results.
///
/// This function:
/// 1. Iterates the inventory for all [`KernelBench`] and [`KernelTest`] impls.
/// 2. Applies the optional filter.
/// 3. Sends a `start` message.
/// 4. For each bench/test, dispatches the kernel on GPU and sends the result.
/// 5. Sends a `done` message.
///
/// # Note
///
/// The actual GPU dispatch is a stub in this version — it emits placeholder
/// results.  The real GPU dispatch is implemented by the runtime crate and
/// wired in after the protocol framework is operational.
pub fn run(args: Args) {
    let stdout = std::io::stdout();
    let mut out = stdout.lock();

    // Collect benches and tests, applying filter.
    let benches: Vec<&'static metaltile_core::KernelBenchEntry> = all_benches()
        .filter(|entry| {
            args.filter.as_ref().is_none_or(|f| {
                entry.as_ref().name().to_ascii_lowercase().contains(&f.to_ascii_lowercase())
            })
        })
        .collect();

    let tests: Vec<&'static metaltile_core::KernelTestEntry> = all_tests()
        .filter(|entry| {
            args.filter.as_ref().is_none_or(|f| {
                entry.as_ref().name().to_ascii_lowercase().contains(&f.to_ascii_lowercase())
            })
        })
        .collect();

    // Send start message.
    let start = ProtocolMessage::Start {
        runner_version: "0.1".to_string(),
        total_benches: benches.len() as u32,
        total_tests: tests.len() as u32,
    };
    let _ = out.write_all(&start.to_json_line());
    let _ = out.flush();

    let mut bench_passed = 0u32;
    let mut bench_failed = 0u32;

    // Run benches.
    if matches!(args.command, Command::Bench) {
        for entry in &benches {
            let bench: &dyn KernelBench = entry.as_ref();
            for &dt in bench.dtypes() {
                match run_single_bench(bench, dt) {
                    Ok(result) => {
                        let msg = ProtocolMessage::BenchResult(result);
                        let _ = out.write_all(&msg.to_json_line());
                        bench_passed += 1;
                    },
                    Err(e) => {
                        let msg = ProtocolMessage::ProtocolError {
                            name: bench.name().to_string(),
                            dtype: dt.label().to_string(),
                            message: e.to_string(),
                        };
                        let _ = out.write_all(&msg.to_json_line());
                        bench_failed += 1;
                    },
                }
                let _ = out.flush();
            }
        }
    }

    let mut test_passed = 0u32;
    let mut test_failed = 0u32;

    // Run tests.
    if matches!(args.command, Command::Test) {
        for entry in &tests {
            let test: &dyn KernelTest = entry.as_ref();
            for &dt in test.dtypes() {
                match run_single_test(test, dt) {
                    Ok(result) => {
                        let msg = ProtocolMessage::TestResult(result.clone());
                        let _ = out.write_all(&msg.to_json_line());
                        if result.passed {
                            test_passed += 1;
                        } else {
                            test_failed += 1;
                        }
                    },
                    Err(e) => {
                        let msg = ProtocolMessage::ProtocolError {
                            name: test.name().to_string(),
                            dtype: dt.label().to_string(),
                            message: e.to_string(),
                        };
                        let _ = out.write_all(&msg.to_json_line());
                        test_failed += 1;
                    },
                }
                let _ = out.flush();
            }
        }
    }

    // Send done.
    let done = ProtocolMessage::Done { bench_passed, bench_failed, test_passed, test_failed };
    let _ = out.write_all(&done.to_json_line());
    let _ = out.flush();
}

/// Run a single benchmark for one dtype.
///
/// This is a stub that emits synthetic timing data.  In production it will
/// allocate GPU buffers, dispatch the kernel, time it, and compute GB/s.
fn run_single_bench(
    bench: &dyn KernelBench,
    dt: DType,
) -> Result<BenchResult, Box<dyn std::error::Error>> {
    let setup = bench.setup(dt);
    let bytes_moved = bench.bytes_moved(&setup);

    // ── Stub: placeholder timing ──
    // TODO: actual GPU dispatch via metaltile-runtime.
    // The real implementation will:
    //   1. Create a Context / device.
    //   2. Compile the kernel via metaltile-codegen.
    //   3. Allocate + initialise buffers per BenchBuffer specs.
    //   4. Warmup loops, then timed loops.
    //   5. Read back output buffers.
    //   6. Compute min/mean latency and GB/s.
    let mt_gbps = if bytes_moved > 0 {
        // Stub: pretend 100 µs kernel time
        (bytes_moved as f64 / 1e9) / (100.0e-6)
    } else {
        0.0
    };

    Ok(BenchResult {
        name: bench.name().to_string(),
        dtype: dt.label().to_string(),
        mt_gbps,
        ref_gbps: None,
        mt_pct: None,
        correct: true,
        min_us: 98.0,
        mean_us: 100.0,
    })
}

/// Run a single correctness test for one dtype.
///
/// This is a stub that always passes.  In production it will:
/// 1. Allocate GPU buffers from TestBuffer inputs.
/// 2. Dispatch the kernel.
/// 3. Read back outputs.
/// 4. Compare against TestBuffer expected values within tolerance.
fn run_single_test(
    test: &dyn KernelTest,
    dt: DType,
) -> Result<TestResult, Box<dyn std::error::Error>> {
    let _setup = test.setup(dt);

    // TODO: actual GPU dispatch and correctness comparison.
    Ok(TestResult {
        name: test.name().to_string(),
        dtype: dt.label().to_string(),
        passed: true,
        max_err: 0.0,
    })
}
